1. Split this string

In [3]:
s = "Hi ,there, Arun!"
s=s.split('.')
s

['Hi ,there, Arun!']

2. Use .format() to print the following string.

Output should be: The diameter of Earth is 12742 kilometers.

In [1]:
planet = "Earth"
diameter = 12742
print("The diameter of {} is {} Kilometers".format(planet, diameter))

The diameter of Earth is 12742 Kilometers


3. In this nest dictionary grab the word "hello"

d = {'k1':[1,2,3,{'tricky':['oh','man','inception',{'target':[1,2,3,'hello']}]}]}

In [ ]:
d = {'k1':[1,2,3,{'tricky':['oh','man','inception',{'target':[1,2,3,'hello']}]}]}
d['k1'][3]['tricky'][3]['target'][3]

'hello'

**Numpy**

In [ ]:
import numpy as np

4.1 Create an array of 10 zeros?

In [ ]:
a=np.zeros(10)
a

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

4.2 Create an array of 10 fives?

In [ ]:
b=np.ones(10)*5
b

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

5. Create an array of all the even integers from 20 to 35


In [ ]:
c=np.arange(20,35,2)
c

array([20, 22, 24, 26, 28, 30, 32, 34])

6. Create a 3x3 matrix with values ranging from 0 to 8


In [ ]:
d=np.arange(9).reshape(3,3)
d

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

7. Concatenate a and b
a = np.array([1, 2, 3]), b = np.array([4, 5, 6])

In [ ]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

c =np.hstack((a,b))

c

array([1, 2, 3, 4, 5, 6])

**Pandas**

8. Create a dataframe with 3 rows and 2 columns

In [5]:
import pandas as pd
data=(['arun',20],['sasi',30],['siva',21])
s=pd.DataFrame(data,columns=['name','age'],index=[1,2,3])
s

name  age
1  arun   20
2  sasi   30
3  siva   21

9. Generate the series of dates from 1st Jan, 2023 to 10th Feb, 2023

In [ ]:
d = pd.date_range(start='1/1/2023', end='10/02/2023', freq='d')    
print(d)

DatetimeIndex(['2023-01-01', '2023-01-02', '2023-01-03', '2023-01-04',
               '2023-01-05', '2023-01-06', '2023-01-07', '2023-01-08',
               '2023-01-09', '2023-01-10',
               ...
               '2023-09-23', '2023-09-24', '2023-09-25', '2023-09-26',
               '2023-09-27', '2023-09-28', '2023-09-29', '2023-09-30',
               '2023-10-01', '2023-10-02'],
              dtype='datetime64[ns]', length=275, freq='D')


10. Create 2D list to DataFrame

lists = [[1, 'aaa', 22], [2, 'bbb', 25], [3, 'ccc', 24]]

In [ ]:
lists = [[1, 'aaa', 22], [2, 'bbb', 25], [3, 'ccc', 24]]
dataframe=pd.DataFrame(lists, columns=["index","name","age"])
dataframe


index name  age
0      1  aaa   22
1      2  bbb   25
2      3  ccc   24